[package]
name = "webpeershare"
version = "0.1.0"
authors = ["Matthew Weeks <scriptjunkie@scriptjunkie.us>"]
edition = "2021"
license = "AGPL 3"

[profile.release]
panic = 'abort'
lto = true

[dependencies]
sha1 = "0.6.0"
base64 = "0.13.0"
smallvec = { version = "1.6.1", features = ["write"] }
